name: ci
on:
  workflow_call:
    secrets:
      CONTAINER_REGISTRY_TOKEN:
        required: true
      CONTAINER_REGISTRY_USERNAME:
        required: true
      CONTAINER_REGISTRY_ENDPOINT:
        required: true
      PAT:
        required: true
  push:
    tags:
      - '*'

jobs:
  docker-build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Determine version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Add Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/hypolia/keycloak
          tags: |
            latest
            buildcache
            ${{ steps.version.outputs.VERSION }}

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And Push
        uses: docker/setup-buildx-action@v5
        with:
          file: ./Dockerfile
          provenance: false
          push: tr
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=hypolia/keycloak:buildcache
          cache-to: type=gha,mode=max,scope=hypolia/keycloak:buildcache
